### ISSUE TITLE
Build error UWP with Xbox Live Unity Plugin

### ISSUE THREAD

**Issue by johnrlisenby** [mixer/interactive-unity-plugin#66]
Hello, 
I am getting a few errors when building out to UWP. I’m using both Xbox Live for Unity and the Mixer plug-ins. The errors I’m getting:
`Assets\MixerInteractive\Source\DLLs\Websocket.cs(274,10): error CS0433: The type 'MonoPInvokeCallbackAttribute' exists in both 'Microsoft.Xbox.Services.UWP.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'”.
`
![mixer error](https://user-images.githubusercontent.com/24777531/38198370-8b321d1e-365a-11e8-91a3-6519c17df9a5.PNG)

The 'Microsoft.Xbox.Services.UWP.CSharp is located in the Xbox Live for Unity folders (Xbox Live/Libs/ UWP.
I’m build in IL2CPP and net 4.6. The reason I’m using these setting is because Unity’s timelines do not play in Master Builds. I'm not sure if this is a Mixer or the Xbox Live plug-in error. The Xbox Live Unity plugin GitHub: https://github.com/Microsoft/xbox-live-unity-plugin

Thanks,

John

**Comment by payzer** [comment]
Thank you for letting us know. We'll fix this (probably with an #ifdef). Websocketsocket.cs is only used for Xbox One builds so if you are building for UWP you are safe to comment it out.

We'll try to fix it this week.

**Comment by payzer** [comment]
Actually, after investigating, this look like an issue in the Xbox Live plugin. The Xbox Live plugin does define it's own MonoPInvokeCallbackAttribute (this conflicts with the one defined in UnityEngine.dll).

So even after putting #if platform defines around websocket.cs, I found other, Xbox Live UWP specific issues.

Could you post the issue on the Xbox Live git repo?

**Comment by johnrlisenby** [comment]
Okay Will do. 

Thanks,

John
